name: Check DB schema structs
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "internal/db/schema/**"
      - "internal/datastore/embedmd/mysql/migrations/**"
      - "internal/datastore/embedmd/postgresql/migrations/**"
jobs:
  check-schema-structs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
      - name: Generate MySQL DB schema structs
        run: make gen/gorm
      - name: Generate PostgreSQL DB schema structs
        run: make gen/gorm DB_TYPE=postgres
      - name: Check if there are uncommitted file changes
        run: |
          clean=$(git status --porcelain)
          if [[ -z "$clean" ]]; then
              echo "Empty git status --porcelain: $clean"
          else
              echo "Uncommitted file changes detected: $clean"
              git diff
              exit 1
          fi
